org: cats-org
space: dev-app
space-developer:
  ldap_users:
  - cat
  users: []
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users:
  - cat
  users: []
  saml_users: []
  ldap_groups: []
space-auditor:
  ldap_users:
  - cat
  users: []
  saml_users: []
  ldap_groups: []
allow-ssh: false
enable-space-quota: false
enable-security-group: false
enable-unassign-security-group: false
enable-remove-users: true
isolation_segment: default
named-security-groups: []
named_quota: ""
metadata: null
