orgs:
- devops
- test
- yasmins-org
- nuras-org
- sarahs-org
- sips-org
- mamas-org
- cats-org
- hemanths-org
- my-org
- ochoas-org
- rays-org
- dev-web
enable-delete-orgs: true
protected_orgs:
- system
