org: sarahs-org
space: dev-web
space-developer:
  ldap_users:
  - sarah
  users: []
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users:
  - sarah
  - nura
  users: []
  saml_users: []
  ldap_groups: []
space-auditor:
  ldap_users:
  - sarah
  users: []
  saml_users: []
  ldap_groups: []
allow-ssh: false
enable-space-quota: false
enable-security-group: false
enable-unassign-security-group: false
enable-remove-users: true
isolation_segment: ""
named-security-groups: []
named_quota: ""
metadata: null
